jets:
    inputs:
        - pt_btagJes
        - eta_btagJes
    labels:
        - HadronConeExclTruthLabelID
        - HadronConeExclTruthLabelPt
        - HadronConeExclExtendedTruthLabelID
        - pt
        - eta
        - mass

tracks_loose:
    inputs:
        - d0
        - z0SinTheta
        - dphi
        - deta
        - qOverP
        - IP3D_signed_d0_significance
        - IP3D_signed_z0_significance
        - phiUncertainty
        - thetaUncertainty
        - qOverPUncertainty
        - numberOfPixelHits
        - numberOfSCTHits
        - numberOfInnermostPixelLayerHits
        - numberOfNextToInnermostPixelLayerHits
        - numberOfInnermostPixelLayerSharedHits
        - numberOfInnermostPixelLayerSplitHits
        - numberOfPixelSharedHits
        - numberOfPixelSplitHits
        - numberOfSCTSharedHits
        - leptonID
    labels:
        - truthOriginLabel

#flow:
#  inputs:
#    - pt
#    - energy
#    - deta
#    - dphi
